### ISSUE TITLE
Minor UX improvement

### ISSUE THREAD

**Issue by jpdefrutos** [dbouget/Raidionics#13]
The location of the "Import patient" button is an unexpected location. Perhaps it should be moved to the top left corner. Alternatively, there should be an option to import patients from the File menu, as this would be a natural place to look for it (if the user doesn't see the aforementioned button).

Additionally, the "Data", "DICOM", and "Save" buttons could be hidden, until a patient has been imported. So as to not attract the attention of the user from the "Import patient" button.

![image](https://user-images.githubusercontent.com/30429725/187206459-c7fa0dfe-7bf1-46d9-a4b7-279a2e467b7d.png)
![image](https://user-images.githubusercontent.com/30429725/187206338-32a4fdf6-6328-4b0e-bda6-a21f447aa7fa.png)

**Comment by andreped** [comment]
I like the idea of being able to import from the File menu, in addition to the already existing solution.

I would expect a lot of users to expect the import button/method to be available in the top left corner of the UI.
