### ISSUE TITLE
Program crash on Mac

### ISSUE THREAD

**Issue by Stitchn99** [dbouget/Raidionics#24]
Each time I upload a NIFTI file and select "Run Segmentation" the program crashes and closes. This happens in 1.0 and 1.1

**Comment by andreped** [comment]
It would be nice to know a little bit more about your setup to debug this further.

Which hardware are you testing the software on? Are you using Windows/Ubuntu/macOS? Which CPU are you using on which computer? 

For instance in my case I am using a Razer Blade Base 15 laptop, Intel core i7-10750H CPU, and Windows 10 Pro.

You can find this information from the `System Information`.

**Comment by Stitchn99** [comment]
Absolutely, very sorry for the limited info. 

Apple M1 Max, 10 core, 64 GB RAM, 32 core GPU, Catalina

**Comment by andreped** [comment]
> Apple M1

Oh, thats unfortunate. There are almost no softwares or libraries that are compatible with the new M1 CPUs. This has to due with the M1 CPUs having a completely different architecture from what people normally use and have used for quite some time (e.g., Intel CPUs).

I don't see us supporting M1 CPUs in the near future. It is really not up to us. Basically none of the libraries we are using in Raidionics support M1, hence, we cannot either.

I would suggest you to use a different computer to test the software. I'm assuming you want to use it in a study, or similar? We may be able to assist you in that, if you don't have any other computer to run Raidionics on.

**Comment by Stitchn99** [comment]
That is quite unfortunate to hear! Thank you for your response, I figure this might be the case. I will see if I cannot get my hands on an intel Mac or Windows and see how that works for my use case. Yes that is exactly right, I appreciate your offer. Thank you.

**Comment by andreped** [comment]
> As an aside, would the slicer extension work?

Have you even been able to install Slicer? Thats surprising to me. I would assume Slicer would have issues, but perhaps they have made some hacks. One big library that Slicer use (or I think it uses) is called VTK, which I believe we have tested with M1 CPUs before with no success.

One of the fundamental libraries we use for inference in both Raidionics and the Slicer plugin is TensorFlow. Tensorflow is used for running the pretrained segmentation models and **does not support M1 CPUs** (or they do, to some minor extent, through a child library called tensorflow-metal, but only a single version, v2.5, which we do not support). So no, that will not work either.

Almost any computer should work with the software. However, we have also found that specific CPUs have issues with it. You can read about that in the troubleshoot section of the wiki:
https://github.com/dbouget/Raidionics/wiki/Frequently-Asked-Questions-(FAQ)#1-the-software-crashes-when-clicking-on-run-segmentation-or-run-reporting

Perhaps I shoud add information regarding the M1 CPU and make it easier for people to find this troubleshoot section in the main README. I can do that tomorrow :)

**Comment by Stitchn99** [comment]
Yes Slicer works well on the M1 Mac. I have also had success with NVIDIA's AI-assisted segmentation algorithm extension. However, your software appears to be much more straightforward interns of extracting volumes from.

**Comment by andreped** [comment]
@Stitchn99 I have now updated the FAQ in the wiki to include the M1 CPU issue:

**Comment by Stitchn99** [comment]
Okay sounds great, so you are certain the slicer extension will not work for the same reason?

**Comment by andreped** [comment]
> Okay sounds great, so you are certain the slicer extension will not work for the same reason?

Yes, but you could try. The first library that will have problems is TensorFlow. We use TF v1.13.1, whereas tensorflow-metal uses tf v2.5, which are very different versions. 

We have been considering updating, but we are unsure if it is just tensorflow that will have issues. I will assume ANTs also will not work. I made a comment on an issue about it in the GitHub repo:
https://github.com/ANTsX/ANTs/issues/1235#issuecomment-1232181239

Lets see what they say. If it works, we could push towards getting that working.

---
But for now, I would use a different computer for running Raidionics. I guess for your study this only needs to be done once on a set of images. Then you can just copy the exported output from Raidionics to the macbook after.

**Comment by andreped** [comment]
More issues related to using M1 chip:
https://developer.apple.com/forums/thread/701358

**Comment by Stitchn99** [comment]
We will have more studies that could use the program. Do you think using a virtualization software such as parallels to run windows would work?

**Comment by andreped** [comment]
> We will have more studies that could use the program. Do you think using a virtualization software such as parallels to run windows would work?

Yes, that will work, as long as you have setup stuff on a different machine.

However, I would think it wouldn't be that challenging to get in touch with someone who has a compatible computer. Did you not find any? Even if you have two studies, you only need to do this twice.

Note that using remote desktop applications like Parallels still require you to have the data on the other computer, and not the M1. So I don't see why you cannot just do it on the other computer in the first place. It is quite fast to do.

BTW: New release today, hopefully!

**Comment by Stitchn99** [comment]
Okay so I was able to get access to another device. 12th generation i9, GTX 3070-Ti, 16GB DDR5 ram, Windows 11. Now I am getting the error that "your cpu supports instructions that this tensor flow binary was not compiled to use: AVX2"

**Comment by andreped** [comment]
> "your cpu supports instructions that this tensor flow binary was not compiled to use: AVX2"

AFAIK, this is a `warning` and not an `error`. What this means is that the program will still run but TensorFlow inference is running a little slower than it could do, if TensorFlow was compiled for AVX2. This is not a problem. You can still use the software. Have you tried?

We just made a new release. Please, try downloading the new release:
https://github.com/dbouget/Raidionics/releases/tag/v1.1.0

And then see the tutorial wiki for how to use it (get started):
https://github.com/dbouget/Raidionics/wiki/Tutorials

Click on the images to see the tutorial video. This should redirect you to YouTube.

Let me know if you still have issues.

**Comment by Stitchn99** [comment]
Thank you for the response. To confirm - do I need to install any dependencies and/or install tensor flow (this is a new computer)

**Comment by andreped** [comment]
> Thank you for the response. To confirm - do I need to install any dependencies and/or install tensor flow (this is a new computer)

No. The program should just work out of the box. But if not, please, let me know such that I can assist you.

**Comment by Stitchn99** [comment]
Unfortunately, after uploading the data and running segmentation per your instructions. The process runs but produces no result.

**Comment by andreped** [comment]
> The process runs but produces no result.

I believe the results may be generated, but they are not disabled by default. This was done as each model produce multiple different segmentations (tumor, brain, and different atlas-generated structures).

See this video for how to choose which result to show:
https://youtu.be/kU_Mt5tUGTA?t=24

**Comment by Stitchn99** [comment]
Okay so now I am seeing something. However tumor was only produced on the flair image and not the T1 Gad image.

**Comment by Stitchn99** [comment]
Okay, I see my mistake. I did not adjust the image modality - it was listed as T1-w not T1CE...Now I have the tumor annotations (2) under T1-CE.

**Comment by andreped** [comment]
Its a new software, which you have never used. It is expected that some features might not be very clear to you, but great that you are telling us what is not intuitive.

We could try to find ways to improve the GUI to better guide the user :)

Let me know if you are having more problems.

**Comment by andreped** [comment]
> Okay, I see my mistake. I did not adjust the image modality - it was listed as T1-w not T1CE...Now I have the tumor annotations (2) under T1-CE.

Oh yeah, note that we **do not** automatically detect which sequence type is used. This cannot be done rigorously through the metadata. However, we have trained a model which can classify sequence types, and are planning on adding it to the next upcoming release. **Stay tuned!**

I would recommend you to **star** the repo, by clicking on the button of the top right in the repository:
![Skjermbilde 2022-09-02 104831](https://user-images.githubusercontent.com/29090665/188102002-0369fbbe-87e3-4f16-8a48-0ac9d3a219c5.png)

That way you will get notifications on new releases (and other stuff), and you will have updates in your github feed. This is how it looks for me (but note that I follow lots of projects, so you can see that other non-Raidionics-related stuff is shown there).
![Skjermbilde 2022-09-02 104857](https://user-images.githubusercontent.com/29090665/188102226-ccb0d5fa-8dfa-402b-9249-fc83e8c1f460.png)

**Comment by Stitchn99** [comment]
Thank you for this info. Unfortunately, I have run into another issue with the gui. When attempting to open an empty patient record, it appears to be throwing an error on the command prompt and failing to do so.

**Comment by andreped** [comment]
> When attempting to open an empty patient record

What do you mean by "empty patient record"? Like loading the result saved on disk, or do what?

**Comment by Stitchn99** [comment]
As in the very first step in loading data

**Comment by Stitchn99** [comment]
It appears that there is an error in the sanity check is what it is saying.

**Comment by andreped** [comment]
> This was occurring during the first step of loading data. However, I was able to correct this (through some user-level issues) and it is working as it should now.

Note sure if I get what the problem was. Could you take some snapshots of what you are trying to do?

Also, since this is not a macOS-related issue. Perhaps we should move this discussion to a new issue (such that it is more easier for others to find this Issue). Could you make a new one?

I will keep this open until M1-support is eventually added.

**Comment by andreped** [comment]
@Stitchn99 But most importantly, if I understand correctly, you are able to run an analysis on an image and the result is generated now? Have you tried running an analysis on a batch?

**Comment by andreped** [comment]
@Stitchn99 Just letting you know, that we will have a test version of Raidionics made available for you to try, that works on M1 chips. Do you still have such a Mac to test on?

**Comment by andreped** [comment]
We have made a pre-release ready for you to try:
https://github.com/dbouget/Raidionics/releases/tag/v1.2.0-alpha

We have run tests on various machines and setups and it seems to be working well. I am therefore closing this issue. If you are experiencing any other issues, please, let us know and we can try to help you further.

**Comment by citystrawman** [comment]
> > Okay sounds great, so you are certain the slicer extension will not work for the same reason?
> 
> Yes, but you could try. The first library that will have problems is TensorFlow. We use TF v1.13.1, whereas tensorflow-metal uses tf v2.5, which are very different versions.
> 
> We have been considering updating, but we are unsure if it is just tensorflow that will have issues. I will assume ANTs also will not work. I made a comment on an issue about it in the GitHub repo: [ANTsX/ANTs#1235 (comment)](https://github.com/ANTsX/ANTs/issues/1235#issuecomment-1232181239)
> 
> I also made a comment on the ANTsPy github repo (Python library, wrapped from ANTs): [ANTsX/ANTsPy#335 (comment)](https://github.com/ANTsX/ANTsPy/issues/335#issuecomment-1232187831)
> 
> Lets see what they say. If it works, we could push towards getting that working.
> 
> But for now, I would use a different computer for running Raidionics. I guess for your study this only needs to be done once on a set of images. Then you can just copy the exported output from Raidionics to the macbook after.

HI, I am also trying to run ANTs on m1 macbook, has anyone solved this issue ?

**Comment by andreped** [comment]
Hello, @citystrawman! Yes, the latest release of Raidionics should work just fine on ARM CPUs. We have solved this quite a while ago by now :) Be sure to download the installer with _arm in the name.
