### ISSUE TITLE
Processing on macOS hangs

### ISSUE THREAD

**Issue by andreped** [dbouget/Raidionics#29]
After the multiprocessing addition, segmentation hangs at the start. This seems to be related to:
https://github.com/mherrmann/fbs/issues/87#issuecomment-508011649

Essentially, in the current state, it is not possible to do any analysis on macOS.

Might also be that we just need to move the spawn stuff to right under the freeze_support():
https://github.com/pyinstaller/pyinstaller/issues/2322#issuecomment-699603755

**Comment by andreped** [comment]
See PR for fix: https://github.com/dbouget/Raidionics/pull/30

Will be merged soon.

**Comment by dbouget** [comment]
Merged in [https://github.com/dbouget/Raidionics/commit/c01b9e70e5fd9389a4ae2d001ec9ba6f9d534a5b](https://github.com/dbouget/Raidionics/commit/c01b9e70e5fd9389a4ae2d001ec9ba6f9d534a5b).
